---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docmost-external-secret
  namespace: tools
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
    namespace: "argocd"
  target:
    name: app-secrets
  data:
  - secretKey: DATABASE_URL
    remoteRef:
      key: secrets/data/docmost
      property: DATABASE_URL
