---
- name: Copy Blocky configuration
  become: true
  template:
    src: "blocky.conf.j2"
    dest: "{{ blocky_config_path }}"

# Pulls the default docker image (Ubuntu)
- name: Pull default Docker image
  community.docker.docker_image:
    name: "{{ default_container_image }}"
    source: pull

- name: Launch Blocky
  docker_container:
    name: blocky
    image: spx01/blocky:latest
    restart: true
    restart_policy: unless-stopped
    volumes:
      - "{{ blocky_config_path }}:/app/config.yml"
    env:
      "TZ": "{{ timezone_value }}"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    labels:
      "com.centurylinklabs.watchtower.enable": "true"
