---
- name: Copy Blocky configuration
  ansible.builtin.template:
    src: "blocky.conf.j2"
    dest: "{{ blocky_config_path }}"
    mode: u=rw,g=r,o=r

- name: Launch Blocky
  community.docker.docker_container:
    name: blocky
    image: spx01/blocky:latest
    restart: true
    restart_policy: unless-stopped
    volumes:
      - "{{ blocky_config_path }}:/app/config.yml"
    env:
      "TZ": "{{ timezone_value }}"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    labels:
      "com.centurylinklabs.watchtower.enable": "true"
