---
- name: Configure Docker Container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ container_image }}"
    pull: true
    volumes: "{{ volumes }}"
    ports: "{{ container_ports }}"
    env: "{{ env }}"
    labels:
      "com.centurylinklabs.watchtower.enable": "true"
