---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name | default "n8n-external-secret" }}
  namespace: {{ .Values.externalSecret.namespace | default "tools" }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "15s" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name | default "vault-k8s-auth" }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ .Values.externalSecret.target.name | default "n8n-secrets" }}
  data:
{{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
{{- end }}
