---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.storage.pv.name }}
  labels:
    type: {{ .Values.storage.pv.labels.type }}
    app: {{ .Values.storage.pv.labels.app }}
spec:
  capacity:
    storage: {{ .Values.storage.pv.capacity }}
  accessModes:
    - {{ .Values.storage.pv.accessModes }}
  persistentVolumeReclaimPolicy: {{ .Values.storage.pv.reclaimPolicy }}
  storageClassName: {{ .Values.storage.pv.storageClassName }}
  nfs:
    server: {{ .Values.storage.pv.nfs.server }}
    path: {{ .Values.storage.pv.nfs.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvc.name }}
  namespace: {{ .Values.storage.pvc.namespace }}
spec:
  accessModes:
    - {{ .Values.storage.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storage.pvc.requests.storage }}
  storageClassName: {{ .Values.storage.pvc.storageClassName }}
