---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ansible/inventory/(host|group)_vars/.*\.yml$
      - id: check-added-large-files

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        exclude: ansible/inventory/(host|group)_vars/.*\.yml$
        args: [--config-file=.yamllint]

  # - repo: https://github.com/ansible/ansible-lint
  #   rev: v6.14.3
  #   hooks:
  #     - id: ansible-lint
  #       files: \.(yaml|yml)$
  #       exclude: ansible/inventory/(host|group)_vars/.*\.yml$
  #       args: ["-c", ".ansible-lint"]

  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v3.0.0-alpha.6
  #   hooks:
  #     - id: prettier
  #       types: [yaml]
  #       exclude: ansible/inventory/(host|group)_vars/.*\.yml$
