---

# Volumes or data dir?
zwavejsui_docker_use_volumes: true
zwavejs_docker_data_dir: "/var/lib/zwavejsui"

zwavejs_container_name: zwavejs

zwavejs_docker_image_name: zwavejs/zwave-js-ui
zwavejs_docker_image_version: latest

zwavejs_root_dir: "/docker/{{ zwavejs_container_name }}"
zwavejs_conf_dir: "{{ zwavejs_root_dir }}"

# Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
# Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
zwavejs_docker_device: ""
