---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  # Custom DNS configuration for home.claydon.co domain
  home.claydon.co.server: |
    home.claydon.co:53 {
        log
        errors
        ready

        # Static DNS entries for SSL-enabled services
        hosts {
            # Point all *.home.claydon.co to k3s load balancer IPs
            192.168.88.59 chat.home.claydon.co
            192.168.88.9  chat.home.claydon.co

            192.168.88.59 docs.home.claydon.co
            192.168.88.9  docs.home.claydon.co

            192.168.88.59 n8n.home.claydon.co
            192.168.88.9  n8n.home.claydon.co

            192.168.88.59 ca.home.claydon.co
            192.168.88.9  ca.home.claydon.co

            192.168.88.59 argocd.home.claydon.co
            192.168.88.9  argocd.home.claydon.co

            # Base domain
            192.168.88.59 home.claydon.co
            192.168.88.9  home.claydon.co

            # Vault (if exposing through ingress)
            192.168.88.59 vault.home.claydon.co
            192.168.88.9  vault.home.claydon.co

            fallthrough
        }

        # Forward everything else to upstream DNS
        forward . 192.168.88.1 1.1.1.1 8.8.8.8

        cache 30
        loop
        reload
        loadbalance
    }
