apiVersion: v1
kind: Secret
metadata:
  name: age-key
  namespace: external-secrets
type: Opaque
stringData:
  age.agekey: |
    # This is a template file that should be encrypted with SOPS
    # Replace this content with your actual Age private key
    # Example format:
    # AGE-SECRET-KEY-1QUWFMHK3PN5VUPTGMVV0ZQPQNRXC3GXVFV8UGVCPVW6LFSRY6YFQJP6GXY
