---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openwebui-external-secret
  namespace: tools
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: openwebui-secrets
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: secrets/data/openwebui
        property: DATABASE_URL
    - secretKey: ollamaUrls
      remoteRef:
        key: secrets/data/openwebui
        property: ollamaUrls
