{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.pvName }}
  labels:
    {{- include "docmost.labels" . | nindent 4 }}
  annotations:
    # Note: The NFS server and path values are now stored in External Secrets
    # but still need to be specified here for the PersistentVolume
    external-secrets.io/nfs-server: "true"
    external-secrets.io/nfs-path: "true"
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClass }}
  nfs:
    server: {{ .Values.persistence.nfs.server }}
    path: {{ .Values.persistence.nfs.path }}
{{- end }}
