---
- name: Update apt packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
    upgrade: true

- name: Install common packages
  become: true
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present

- name: Create user
  ansible.builtin.user:
    name: "{{ common_user }}"
    shell: /bin/bash
    groups: sudo
    append: true
    create_home: true
    state: present

- name: Limit journalctl size
  ansible.builtin.lineinfile:
    path: "/etc/systemd/journald.conf"
    regexp: "^SystemMaxUse="
    line: "SystemMaxUse=100M"
