---
- name: "Custom Component | {{ item.name }}"
  block:
    - name: "Check {{ item.name }} presence"
      register: "custom_component_installed"
      ansible.builtin.stat:
        path: "{{ home_assistant.component_dir + '/' + item.name }}"

    - name: "Create {{ item.name }} directory"
      when: "not custom_component_installed.stat.exists"
      ansible.builtin.file:
        owner: root
        group: root
        path: "{{ home_assistant.component_dir + '/' + item.name }}"
        state: "directory"
        mode: 0750

    - name: "Install {{ item.name }}"
      when: "not custom_component_installed.stat.exists"
      ansible.builtin.unarchive:
        src: "{{ item.repo }}"
        dest: "{{ home_assistant.component_dir + '/' + item.name }}"
        remote_src: true
        mode: "u=rwX,g=rX,o="
