---
- name: Setup the MySQL Database
  community.mysql.mysql_db:
    name: homeassistant
    state: present
    login_host: 127.0.0.1
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Ensure homeassistant group exists
  ansible.builtin.group:
    name: "{{ home_assistant.config_dir_group }}"
    state: present

- name: Adding homeassistant user to homeassistant group
  ansible.builtin.user:
    name: "{{ home_assistant.config_dir_user }}"
    groups: "{{ home_assistant.config_dir_group }}"
    state: present
    append: true

- name: Create backup directory
  ansible.builtin.file:
    path: "{{ home_assistant_backup_path }}"
    state: directory
    owner: "{{ home_assistant.config_dir_user }}"
    group: "{{ home_assistant.config_dir_group }}"
    mode: u=rw,g=r,o=r

- name: Force all notified handlers to run at this point
  ansible.builtin.meta: flush_handlers

- name: Get latest release of a public repository
  community.general.github_release:
    user: rikdc
    repo: home-assistant-config
    action: latest_release
    prerelease: true
  register: ha_config_latest_release

- name: Clone a home-assistant configuration repository
  ansible.builtin.git:
    repo: https://github.com/rikdc/home-assistant-config.git
    dest: "{{ homeassistant_data_directory }}"
    clone: true
    update: false
    version: "{{ ha_config_latest_release }}"

- name: Copy secrets.
  become: true
  ansible.builtin.copy:
    mode: u=rw,g=r,o=r
    src: files/secrets.yaml
    dest: "{{ homeassistant_data_directory }}/secrets.yaml"

- name: Create custom_components/ directory
  ansible.builtin.file:
    path: "{{ homeassistant_data_directory }}/custom_components/"
    state: directory
    owner: "{{ home_assistant.config_dir_user }}"
    group: "{{ home_assistant.config_dir_group }}"
    mode: u=rw,g=r,o=r
  become: true

- name: "Install custom components"
  ansible.builtin.include_tasks: custom-components.yml
  with_items:
    - "{{ home_assistant.custom_components }}"

- name: Create themes/ directory
  ansible.builtin.file:
    path: "{{ home_assistant.config_dir }}/themes/"
    state: directory
    owner: "{{ home_assistant.config_dir_user }}"
    group: "{{ home_assistant.config_dir_group }}"
    mode: u=rw,g=r,o=r
  become: true

- name: Create www/ directory
  ansible.builtin.file:
    path: "{{ home_assistant.config_dir }}/www/"
    state: directory
    owner: "{{ home_assistant.config_dir_user }}"
    group: "{{ home_assistant.config_dir_group }}"
    mode: u=rw,g=r,o=r
  become: true

- name: "Include all frontend components"
  ansible.builtin.include_tasks: www.yml
  with_items:
    - "{{ home_assistant.frontend_components }}"

- name: Start Home Assistant Docker containers
  community.docker.docker_container:
    name: "{{ home_assistant.docker_name }}"
    image: "{{ home_assistant.docker_image }}"
    detach: false
    ports:
      - "8123:8123/tcp"
    restart: true
    dns_servers:
      - 192.168.88.211
      - 192.168.88.226
    volumes:
      - "{{ homeassistant_data_directory }}:/config"
