---
- name: "WWW Component {{ item.name }}"
  block:
    - name: "Check component presence: {{ item.name }}"
      register: "www_component_installed"
      ansible.builtin.stat:
        path: "{{ home_assistant.config_dir + '/www/community/' + item.name }}"

    - name: "Create directory: {{ item.name }}"
      when: "not www_component_installed.stat.exists"
      ansible.builtin.file:
        owner: root
        group: root
        path: "{{ home_assistant.config_dir + '/www/community/' + item.name }}"
        state: "directory"
        mode: 0750

    - name: "Install {{ item.name }}"
      when: "not www_component_installed.stat.exists"
      ansible.builtin.unarchive:
        src: "{{ item.repo }}"
        dest: "{{ home_assistant.config_dir + '/www/community/' + item.name }}"
        remote_src: true
        mode: "u=rwX,g=rX,o="
