---
# Default values for homepage Helm chart

replicaCount: 1

serviceAccount:
  name: eso-vault-auth
  namespace: tools

# External Secrets configuration
externalSecrets:
  enabled: true
  secretStore:
    name: vault-kv
    kind: ClusterSecretStore
  data:
    # MikroTik widget secrets (already implemented)
    - secretKey: HOMEPAGE_VAR_MIKROTIK_URL
      remoteRef:
        key: homepage
        property: WIDGET_MIKROTIK_URL
    - secretKey: HOMEPAGE_VAR_MIKROTIK_USERNAME
      remoteRef:
        key: homepage
        property: WIDGET_MIKROTIK_USERNAME
    - secretKey: HOMEPAGE_VAR_MIKROTIK_PASSWORD
      remoteRef:
        key: homepage
        property: WIDGET_MIKROTIK_PASSWORD

    # Example for Matrix link
    - secretKey: HOMEPAGE_VAR_MATRIX_URL
      remoteRef:
        key: homepage/links/matrix
        property: url

    # Example for Jellyfin link
    - secretKey: HOMEPAGE_VAR_JELLYFIN_URL
      remoteRef:
        key: homepage/links/jellyfin
        property: url
