---
# enable or disable the application
jellyfin_enabled: false
jellyfin_available_externally: false

# directories
jellyfin_config_directory: "{{ docker_home }}/jellyfin/config"
jellyfin_movies_directory: "{{ movies_root }}"
jellyfin_tv_directory: "{{ tv_root }}"
jellyfin_books_directory: "{{ books_root }}"
jellyfin_audiobooks_directory: "{{ audiobooks_root }}"

# permissions
jellyfin_movies_permissions: "rw"
jellyfin_tv_permissions: "rw"
jellyfin_books_permissions: "rw"
jellyfin_audiobooks_permissions: "rw"

# uid / gid
jellyfin_user_id: "0"
jellyfin_group_id: "0"

# network
jellyfin_hostname: "jellyfin"
jellyfin_port_http: "8096"
jellyfin_port_https: "8920"

# specs
jellyfin_memory: "1g"

jellyfin_volumes:
    - { name: 'testuser1', groups: 'wheel' }
