---
apiVersion: v2
name: n8n
version: 4.1.2
dependencies:
  - name: app-template
    version: 4.1.2
    repository: https://bjw-s-labs.github.io/helm-charts/
  - name: qdrant
    version: 1.14.1
    repository: https://qdrant.github.io/qdrant-helm
