---
externalSecret:
  name: n8n-external-secret
  namespace: tools
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-k8s-auth
    kind: ClusterSecretStore
  target:
    name: n8n-secrets
  data:
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: secrets/n8n
        property: N8N_ENCRYPTION_KEY
    - secretKey: DATABASE_URL
      remoteRef:
        key: secrets/n8n
        property: DATABASE_URL
    - secretKey: N8N_BASIC_AUTH_USER
      remoteRef:
        key: secrets/n8n
        property: N8N_BASIC_AUTH_USER
    - secretKey: N8N_BASIC_AUTH_PASSWORD
      remoteRef:
        key: secrets/n8n
        property: N8N_BASIC_AUTH_PASSWORD
app-template:
  image:
    repository: n8nio/n8n
    tag: latest
  persistence:
    config:
      enabled: true
      type: nfs
      server: nas.home.lan
      path: /volume1/docker/n8n
      mountPath: /home/node/.n8n
  envFrom:
    - secretRef:
        name: n8n-secrets
  service:
    main:
      ports:
        http:
          port: 5678
  ingress:
    main:
      enabled: true
      hosts:
        - host: n8n.home.lan
          paths:
            - path: /
              pathType: Prefix
