---
storage:
  pv:
    name: n8n-config-pv
    labels:
      type: config
      app: n8n
    capacity: 1Gi
    accessModes: ReadWriteMany
    reclaimPolicy: Retain
    storageClassName: nfs-storage
    nfs:
      server: nas.home.lan
      path: /volume1/docker/n8n
  pvc:
    name: n8n-config-pvc
    namespace: tools
    accessModes: ReadWriteMany
    requests:
      storage: 1Gi
    storageClassName: nfs-storage

externalSecret:
  namespace: tools
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: n8n-secrets
  data:
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: n8n
        property: N8N_ENCRYPTION_KEY
    - secretKey: N8N_BASIC_AUTH_USER
      remoteRef:
        key: n8n
        property: N8N_BASIC_AUTH_USER
    - secretKey: N8N_BASIC_AUTH_PASSWORD
      remoteRef:
        key: n8n
        property: N8N_BASIC_AUTH_PASSWORD
    - secretKey: DB_POSTGRESDB_HOST
      remoteRef:
        key: n8n
        property: DB_POSTGRESDB_HOST
    - secretKey: DB_POSTGRESDB_USER
      remoteRef:
        key: n8n
        property: DB_POSTGRESDB_USER
    - secretKey: DB_POSTGRESDB_PASSWORD
      remoteRef:
        key: n8n
        property: DB_POSTGRESDB_PASSWORD

app-template:
  namespaceOverride: tools

  controllers:
    n8n:
      type: deployment
      pod:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000

      containers:
        app:
          image:
            repository: n8nio/n8n
            tag: 1.101.0
          env:
            DB_TYPE: postgresdb
            DB_POSTGRESDB_HOST:
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: DB_POSTGRESDB_HOST
            DB_POSTGRESDB_USER:
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: DB_POSTGRESDB_USER
            DB_POSTGRESDB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: DB_POSTGRESDB_PASSWORD
            N8N_ENCRYPTION_KEY:
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: N8N_ENCRYPTION_KEY
            N8N_BASIC_AUTH_USER:
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: N8N_BASIC_AUTH_USER
            N8N_BASIC_AUTH_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: N8N_BASIC_AUTH_PASSWORD

          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi

  persistence:
    data:
      existingClaim: n8n-config-pvc

  service:
    n8n:
      controller: n8n
      ports:
        http:
          port: 5678
  ingress:
    n8n:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts:
        - host: n8n.home.lan
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - n8n.home.lan
          secretName: homepage-tls-certificate

qdrant:
  replicaCount: 1

  image:
    repository: docker.io/qdrant/qdrant
    tag: v1.14.1
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    ports:
      - name: http
        port: 6333
        targetPort: 6333
        protocol: TCP
        checksEnabled: true
      - name: grpc
        port: 6334
        targetPort: 6334
        protocol: TCP
        checksEnabled: false
      - name: p2p
        port: 6335
        targetPort: 6335
        protocol: TCP
        checksEnabled: false

  persistence:
    accessModes:
      - ReadWriteMany
    size: 10Gi
    storageClassName: nfs-storage
    annotations: {}

  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: qdrant.home.lan
        paths:
          - path: /
            pathType: Prefix
            servicePort: 6333
    tls:
      - hosts:
          - qdrant.home.lan
        secretName: homepage-tls-secret
