galaxy_info:
  author: rikdc
  description: Configures and runs the zwavejs-ui docker container
  license: MIT
  min_ansible_version: "2.1"
  platform:
    - name: "Ubuntu"
      versions:
        - "bionic"
        - "focal"
        - "jammy"
  galaxy_tags: []
dependencies: []
