apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-secrets
  namespace: homepage
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: homepage-secrets
  data:
    - secretKey: WIDGET_MIKROTIK_PASSWORD
      remoteRef:
        key: secrets/homepage
        property: WIDGET_MIKROTIK_PASSWORD
    - secretKey: WIDGET_MIKROTIK_URL
      remoteRef:
        key: secrets/homepage
        property: WIDGET_MIKROTIK_URL
    - secretKey: WIDGET_MIKROTIK_USERNAME
      remoteRef:
        key: secrets/homepage
        property: WIDGET_MIKROTIK_USERNAME
