---
# Default variables for k3s_setup role

# Common settings
k3s_setup_packages_update: true
k3s_setup_packages_upgrade: true

# Helm settings
k3s_setup_helm_charts:
  - name: csi-driver-nfs
    repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts

# NFS CSI driver settings
k3s_setup_nfs_csi_namespace: kube-system
k3s_setup_nfs_csi_kubelet_dir: /var/lib/kubelet

# Node settings
k3s_setup_server_url_template: "https://{{ hostvars['k3s-controller']['ansible_host'] }}:6443"
k3s_setup_node_token_path: /var/lib/rancher/k3s/server/node-token
