---
apiVersion: v1
kind: Namespace
metadata:
  name: ssl-certificates
  labels:
    name: ssl-certificates
    app.kubernetes.io/name: ssl-certificates
    app.kubernetes.io/component: platform
    app.kubernetes.io/part-of: homelab
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
---
apiVersion: v1
kind: Namespace
metadata:
  name: networking
  labels:
    name: networking
    app.kubernetes.io/name: networking
    app.kubernetes.io/component: platform
    app.kubernetes.io/part-of: homelab
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
