---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-k8s-auth
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  provider:
    vault:
      server: "https://vault.home.lan:8200"
      path: "pki_homelab"
      version: "v2"
      caProvider:
        type: Secret
        name: vault-ca
        key: ca.crt
        namespace: external-secrets
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso"
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"
