---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: wildcard-home-claydon-co
  namespace: ssl-certificates
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  path: "pki_homelab/issue/home-claydon-co"
  method: "POST"
  parameters:
    common_name: "*.home.claydon.co"
    alt_names: "*.home.claydon.co"
    ttl: "8760h"
    key_type: "ec"
    key_bits: 256
  resultType: "Data"
  provider:
    server: "https://vault.home.lan:8200"
    auth:
      kubernetes:
        mountPath: "kubernetes"
        role: "eso"

---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: wildcard-home-claydon-co
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  path: "pki_homelab/issue/home-claydon-co"
  method: "POST"
  parameters:
    common_name: "*.home.claydon.co"
    alt_names: "*.home.claydon.co"
    ttl: "8760h"
    key_type: "ec"
    key_bits: 256
  resultType: "Data"
  provider:
    server: "https://vault.home.lan:8200"
    auth:
      kubernetes:
        mountPath: "kubernetes"
        role: "eso"

---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: wildcard-home-claydon-co
  namespace: tools
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  path: "pki_homelab/issue/home-claydon-co"
  method: "POST"
  parameters:
    common_name: "*.home.claydon.co"
    alt_names: "*.home.claydon.co"
    ttl: "8760h"
    key_type: "ec"
    key_bits: 256
  resultType: "Data"
  provider:
    server: "https://vault.home.lan:8200"
    auth:
      kubernetes:
        mountPath: "kubernetes"
        role: "eso"

---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: wildcard-home-claydon-co
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  path: "pki_homelab/issue/home-claydon-co"
  method: "POST"
  parameters:
    common_name: "*.home.claydon.co"
    alt_names: "*.home.claydon.co"
    ttl: "8760h"
    key_type: "ec"
    key_bits: 256
  resultType: "Data"
  provider:
    server: "https://vault.home.lan:8200"
    auth:
      kubernetes:
        mountPath: "kubernetes"
        role: "eso"

---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: wildcard-home-claydon-co
  namespace: networking
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  path: "pki_homelab/issue/home-claydon-co"
  method: "POST"
  parameters:
    common_name: "*.home.claydon.co"
    alt_names: "*.home.claydon.co"
    ttl: "8760h"
    key_type: "ec"
    key_bits: 256
  resultType: "Data"
  provider:
    server: "https://vault.home.lan:8200"
    auth:
      kubernetes:
        mountPath: "kubernetes"
        role: "eso"
