---
# Distribute wildcard certificate to kube-system namespace for Traefik default certificate
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wildcard-home-claydon-co-tls-kube-system
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "720h"
  secretStoreRef:
    name: vault-k8s-auth
    kind: ClusterSecretStore
  target:
    name: wildcard-home-claydon-co-tls
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      data:
        tls.key: "{{ .private_key }}"
        tls.crt: |
          {{- $leaf := .certificate -}}
          {{- $chain := .ca_chain | join "\n" -}}
          {{ printf "%s\n%s\n" $leaf $chain }}
  dataFrom:
    - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: VaultDynamicSecret
        name: wildcard-home-claydon-co

---
# Distribute wildcard certificate to tools namespace for applications
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wildcard-home-claydon-co-tls-tools
  namespace: tools
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "720h"
  secretStoreRef:
    name: vault-k8s-auth
    kind: ClusterSecretStore
  target:
    name: wildcard-home-claydon-co-tls
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      data:
        tls.key: "{{ .private_key }}"
        tls.crt: |
          {{- $leaf := .certificate -}}
          {{- $chain := .ca_chain | join "\n" -}}
          {{ printf "%s\n%s\n" $leaf $chain }}
  dataFrom:
    - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: VaultDynamicSecret
        name: wildcard-home-claydon-co

---
# Distribute wildcard certificate to argocd namespace
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wildcard-home-claydon-co-tls-argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "720h"
  secretStoreRef:
    name: vault-k8s-auth
    kind: ClusterSecretStore
  target:
    name: wildcard-home-claydon-co-tls
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      data:
        tls.key: "{{ .private_key }}"
        tls.crt: |
          {{- $leaf := .certificate -}}
          {{- $chain := .ca_chain | join "\n" -}}
          {{ printf "%s\n%s\n" $leaf $chain }}
  dataFrom:
    - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: VaultDynamicSecret
        name: wildcard-home-claydon-co

---
# Distribute wildcard certificate to networking namespace for CA site
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wildcard-home-claydon-co-tls-networking
  namespace: networking
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "720h"
  secretStoreRef:
    name: vault-k8s-auth
    kind: ClusterSecretStore
  target:
    name: wildcard-home-claydon-co-tls
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      data:
        tls.key: "{{ .private_key }}"
        tls.crt: |
          {{- $leaf := .certificate -}}
          {{- $chain := .ca_chain | join "\n" -}}
          {{ printf "%s\n%s\n" $leaf $chain }}
  dataFrom:
    - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: VaultDynamicSecret
        name: wildcard-home-claydon-co
