---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ssl-certificates
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/home-network-config.git  # Update this URL
    targetRevision: HEAD
    path: k3s/platform/ssl-certificates
    directory:
      recurse: false
      exclude: |
        templates/
        README.md
        argocd-app.yaml
        vault-ca.pem
        vault-ca-b64.txt
  destination:
    server: https://kubernetes.default.svc
    namespace: ssl-certificates
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
