---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: sops-secret-store
spec:
  provider:
    sops:
      age:
        secretRef:
          name: age-key
          key: age.agekey
          namespace: external-secrets
