- name: playbook to set up a MQTT server
  hosts: servers
  gather_facts: false
  debugger: on_failed
  #become: true

  # tasks:
  #   # - include_role:
  #   #     name: prepare-raspberry
  #   - include_role:
  #       name: gitserver-config

  # # Prerequisites:
  # # - install ssh
  # # - set up ssh for certificate only logins
  # # - install python
  # # - configure login account with sudo permissions

  # - hosts: homeauto
  #   roles:
  #     - common
  #     - fish
  #     #    - mount-home
  #     - vm
  #     - docker
  #     - ssmtp
  #     - openzwave
  #     - mosquitto
  #     - influxdb
  #     - openhab
  #     #    - grafana # not working for some reason
  #     - screengrab
  #     - share-ohconf
  #     - multitail
  #     - glances
  #     - sensorreporter
  #     - tripwire

  # - name: Ensure US locale exists
  #   hosts: all
  #   community.general.locale_gen:
  #     name: en_US.UTF-8
  #     state: present
  # ---

  # Add the docker group if it doesn't already exist:

  #  sudo groupadd docker

  # Add the connected user "$USER" to the docker group. Change the user name to match your preferred user if you do not want to use your current user:

  #  sudo gpasswd -a $USER docker

  # Either do a newgrp docker or log out/in to activate the changes to groups.

  # You can use

  #  docker run hello-world

  # to check if you can run docker without sudo.

  tasks:
    - name: "Create Docker directory"
      file:
        path: "{{ item.path }}"
        mode: "{{item.mode}}"
        state: directory
      with_items:
        - { path: "~/mosquitto/config", mode: "0777" }
        - { path: "~/mosquitto/data", mode: "0755" }

    - name: Sync config
      synchronize:
        src: files/mosquitto.conf
        dest: "{{ paths.mosquitto }}"
      #notify:
      #- change ownership
      #- restart filebeat

    - name: Create a data container
      community.docker.docker_container:
        name: mosquitto
        image: eclipse-mosquitto
        restart_policy: always
        volumes:
          - ~/mosquitto/config:/mosquitto/config
          - ~/mosquitto/data:/mosquitto/data
        ports:
          - "8883:8883"
          - "9001:9001"
