apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: age-key-external-secret
  namespace: external-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: sops-secret-store
    kind: ClusterSecretStore
  target:
    name: age-key
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k3s/secrets/global/age-key.enc.yaml
