---
ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: git.home.lan
      paths:
        - path: /
          pathType: Prefix
  tls: []

gitea:
  config:
    database:
      DB_TYPE: postgres
      NAME: gitea
      SCHEMA: public
      SSL_MODE: disable
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true
    redis:
      HOST: gitea-redis-master.default.svc.cluster.local
      PORT: 6379

  env:
    # Redis config
    - name: GITEA_REDIS_HOST
      value: gitea-redis-master.default.svc.cluster.local
    - name: GITEA_REDIS_PORT
      value: "6379"
  admin:
    username: ""
    password: ""
    email: ""
    existingSecret: gitea-admin-credentials


  additionalConfigFromEnvs:
    - name: GITEA__DATABASE__USER
      valueFrom:
        secretKeyRef:
          name: vault-gitea-secrets
          key: GITEA_DATABASE_USER
    - name: GITEA__DATABASE__PASSWD
      valueFrom:
        secretKeyRef:
          name: vault-gitea-secrets
          key: GITEA_DATABASE_PASSWD
    - name: GITEA__DATABASE__HOST
      valueFrom:
        secretKeyRef:
          name: vault-gitea-secrets
          key: GITEA_DATABASE_HOST
    - name: GITEA__REDIS__PASSWD
      valueFrom:
        secretKeyRef:
          name: vault-gitea-secrets
          key: GITEA_REDIS_PASSWD

  # Disable built-in PostgreSQL as we're using external database
  postgresql:
    enabled: false

  postgresql-ha:
    enabled: false

  # Configure Redis for caching
  redis-cluster:
    enabled: false
    cluster:
      nodes: 0
      replicas: 0

  redis:
    enabled: true
    #architecture: standalone
    # auth:
    #   enabled: true
    #   existingSecret: gitea-redis-credentials
    #   existingSecretPasswordKey: redis-password

  # Use the persistent volume claim we created
  persistence:
    enabled: true
    existingClaim: gitea-data-pvc

  namespace: tools
