---
- name: Set up k3s Kubernetes cluster
  hosts: k3s
  become: true
  roles:
    - role: k3s_setup

- name: Set up persistent storage
  hosts: k3s-controller
  become: true
  roles:
    - role: k8s_persistent_storage
      vars:
        kubeconfig_path: /etc/rancher/k3s/k3s.yaml

- name: Wait for PVCs to be bound
  hosts: k3s-controller
  become: true
  tasks:
    - name: Wait for PVCs to be bound
      shell: |
        kubectl get pvc -o jsonpath='{.items[*].status.phase}' | grep -q "Bound"
      register: pvc_bound_check
      retries: 10
      delay: 5
      until: pvc_bound_check.rc == 0
      ignore_errors: yes
      changed_when: false
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
