---
galaxy_info:
  author: Your Name
  description: Role to set up k3s Kubernetes cluster
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - kubernetes
    - k3s
    - cluster

dependencies: []
