---
# Common tasks for all k3s nodes

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: k3s_setup_packages_update | bool
  tags: [k3s, packages]

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
  when: k3s_setup_packages_upgrade | bool
  tags: [k3s, packages]

- name: Install NFS client
  ansible.builtin.package:
    name: nfs-common
    state: present
    force: yes
  tags: [k3s, nfs]
