---
# Main tasks file for k3s_setup role

- name: Include common setup tasks
  include_tasks: common.yml
  tags: [k3s, common]

- name: Include controller setup tasks
  include_tasks: controller.yml
  when: inventory_hostname == 'k3s-controller'
  tags: [k3s, controller]

- name: Include node setup tasks
  include_tasks: node.yml
  when: inventory_hostname == 'k3s-node1' or inventory_hostname == 'k3s-node2'
  tags: [k3s, node]
