---
# Tasks for k3s node setup

- name: Wait for k3s controller to generate node-token
  delegate_to: k3s-controller
  become: true
  shell: |
    test -f {{ k3s_node_token_path }}
  retries: 10
  delay: 5
  register: token_check
  until: token_check.rc == 0
  tags: [k3s, node]

- name: Fetch node-token from k3s controller
  delegate_to: k3s-controller
  become: true
  fetch:
    src: "{{ k3s_node_token_path }}"
    dest: /tmp/node-token
    flat: yes
  tags: [k3s, node]

- name: Install k3s
  shell: |
    curl -sfL https://get.k3s.io | K3S_URL={{ k3s_server_url_template }} K3S_TOKEN={{ lookup('file', '/tmp/node-token') }} sh -
  args:
    creates: /usr/local/bin/k3s
  tags: [k3s, node]
