---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://192.168.88.43:8200"
      path: "secrets"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
