---
secretStore:
  name: vault-backend

vault:
  server: "https://vault.home.lan:8200"
  path: "secrets"
  version: "v2"
  caProvider:
    name: "vault-ca"
    key: "ca.crt"
    namespace: "external-secrets"
  auth:
    tokenSecretRef:
      name: "vault-token"
      key: "token"
      namespace: "vault"
