---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.name | default "vault-backend" }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server }}"
      path: {{ .Values.vault.path | default "secrets" }}
      version: {{ .Values.vault.version | default "v2" }}
      caProvider:
        type: ConfigMap
        name: {{ .Values.vault.caProvider.name | default "vault-ca" }}
        key: {{ .Values.vault.caProvider.key | default "ca.crt" }}
        namespace: {{ .Values.vault.caProvider.namespace | default "external-secrets" }}
      auth:
        tokenSecretRef:
          name: {{ .Values.vault.auth.tokenSecretRef.name | default "vault-token" }}
          key: {{ .Values.vault.auth.tokenSecretRef.key | default "token" }}
          namespace: {{ .Values.vault.auth.tokenSecretRef.namespace | default "argocd" }}
