---
homeassistant_enabled: false
homeassistant_available_externally: false

home_assistant_docker_image_version: latest
home_assistant_docker_memory: 1G
home_assistant_docker_labels: {}
home_assistant_docker_network: bridge
home_assistant_docker_publish_ports:
  - 127.0.0.1:8123:8123

# directories
homeassistant_data_directory: "{{ docker_home }}/homeassistant"
home_assistant_backup_path: "{{ docker_home }}/backups"

# network
homeassistant_port: "8123"
homeassistant_hostname: "homeassistant"

# specs
homeassistant_memory: 1g

