apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-external-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: sops-secret-store
    kind: ClusterSecretStore
  target:
    name: example-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k3s/secrets/apps/example/secrets.enc.yaml
