---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-external-secret
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: example-secrets
    creationPolicy: Owner
  data:
    - secretKey: APP_SECRET
      remoteRef:
        key: secrets/data/example
        property: APP_SECRET
