---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-secrets
  namespace: tools
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: app-secrets
  data:
    - secretKey: APP_SECRET
      remoteRef:
        key: docmost
        property: APP_SECRET
