{{- if and .Values.certmanager.enabled .Values.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ca-key-pair
  namespace: cert-manager
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-pki-backend  # Changed from vault-backend to vault-pki-backend
    kind: ClusterSecretStore
  target:
    name: ca-key-pair
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: /intermediate/cert
    - secretKey: tls.key
      remoteRef:
        key: /intermediate/private_key
{{- end }}
---
{{- if and .Values.certmanager.enabled .Values.externalSecrets }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
  namespace: cert-manager
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
spec:
  ca:
    secretName: ca-key-pair
{{- end }}
