{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    {{- include "cert-manager.labels" . | nindent 4 }}
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
  namespaceSelector:
    matchNames:
      - cert-manager
  endpoints:
    - port: metrics
      interval: {{ .Values.monitoring.interval | default "30s" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cert-manager-alerts
  namespace: cert-manager
  labels:
    {{- include "cert-manager.labels" . | nindent 4 }}
    release: prometheus
spec:
  groups:
    - name: cert-manager
      rules:
        # Certificate expiration alerts
        - alert: CertificateExpirationCritical
          expr: certmanager_certificate_expiration_timestamp_seconds - time() < ({{ .Values.monitoring.alerts.criticalExpiry }} * 24 * 3600)
          for: 1h
          labels:
            severity: critical
          annotations:
            description: 'Certificate {{ "{{" }} $labels.name {{ "}}" }} in namespace {{ "{{" }} $labels.namespace {{ "}}" }} expires in less than {{ .Values.monitoring.alerts.criticalExpiry }} days'
            summary: "Certificate expiring soon"

        - alert: CertificateExpirationWarning
          expr: certmanager_certificate_expiration_timestamp_seconds - time() < ({{ .Values.monitoring.alerts.warningExpiry }} * 24 * 3600)
          for: 1h
          labels:
            severity: warning
          annotations:
            description: 'Certificate {{ "{{" }} $labels.name {{ "}}" }} in namespace {{ "{{" }} $labels.namespace {{ "}}" }} expires in less than {{ .Values.monitoring.alerts.warningExpiry }} days'
            summary: "Certificate expiration approaching"

        # Certificate renewal failure alerts
        - alert: CertificateRenewalFailure
          expr: certmanager_certificate_renewal_errors_total > 0
          for: 1h
          labels:
            severity: critical
          annotations:
            description: 'Certificate {{ "{{" }} $labels.name {{ "}}" }} in namespace {{ "{{" }} $labels.namespace {{ "}}" }} failed to renew'
            summary: "Certificate renewal failed"

        # External Secret sync alerts
        - alert: ExternalSecretSyncFailure
          expr: rate(external_secrets_sync_failed_total[5m]) > 0
          for: 15m
          labels:
            severity: critical
          annotations:
            description: 'External Secret {{ "{{" }} $labels.name {{ "}}" }} in namespace {{ "{{" }} $labels.namespace {{ "}}" }} failed to sync'
            summary: "External Secret sync failed"

        # cert-manager controller health
        - alert: CertManagerControllerDown
          expr: up{job="cert-manager"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            description: "cert-manager controller has been down for more than 5 minutes"
            summary: "cert-manager controller is down"

        # High error rate
        - alert: CertManagerHighErrorRate
          expr: rate(certmanager_controller_errors_total[5m]) > {{ .Values.monitoring.alerts.errorRateThreshold }}
          for: 15m
          labels:
            severity: warning
          annotations:
            description: "cert-manager is experiencing a high error rate (> {{ .Values.monitoring.alerts.errorRateThreshold }})"
            summary: "High error rate in cert-manager"
{{- end }}
