---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-pki-backend
spec:
  provider:
    vault:
      server: "{{ .Values.externalSecrets.vault.server }}"
      path: "{{ .Values.externalSecrets.vault.pkiPath }}"
      caProvider:
        type: ConfigMap
        name: "vault-ca"
        key: "ca.crt"
        namespace: external-secrets
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
          namespace: "argocd"
