---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-pki-backend
spec:
  provider:
    vault:
      server: "https://vault.home.lan:8200"
      path: "{{ .Values.externalSecrets.vault.pkiPath }}"
      caProvider:
        type: ConfigMap
        name: "vault-ca"
        key: "ca.crt"
        namespace: external-secrets
      auth:
        # Option 1: Token Auth (reusing existing token)
        tokenSecretRef:
          name: "vault-token"
          key: "token"
          namespace: "argocd"

        # Option 2: Kubernetes Auth (try another day)
        # kubernetes:
        #   mountPath: "kubernetes"
        #   role: "cert-manager"
        #   serviceAccountRef:
        #     name: "cert-manager"
        #     namespace: "cert-manager"
