---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.gitea.externalSecret.name | default "vault-gitea-secrets" }}
  namespace: {{ .Values.gitea.externalSecret.namespace | default .Release.Namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.gitea.externalSecret.secretStoreRef.name | default "vault-backend" }}
    kind: {{ .Values.gitea.externalSecret.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ .Values.gitea.externalSecret.targetName | default "gitea-secrets" }}
  data:
    - secretKey: GITEA_DATABASE_USER
      remoteRef:
        key: secrets/gitea
        property: GITEA_DATABASE_USER
    - secretKey: GITEA_DATABASE_PASSWD
      remoteRef:
        key: secrets/gitea
        property:  GITEA_DATABASE_PASSWD
    - secretKey: GITEA_DATABASE_HOST
      remoteRef:
        key: secrets/gitea
        property: GITEA_DATABASE_HOST
    - secretKey: GITEA_REDIS_PASSWD
      remoteRef:
        key: secrets/gitea
        property: GITEA_REDIS_PASSWD
