---
- name: Setup | Setup Synology for Docker
  ansible.builtin.include_tasks: roles/docker/tasks/synology.yaml
  when: ansible_facts['board_vendor'] == 'Synology'

- name: Setup | Setup Ubuntu for Docker
  ansible.builtin.include_tasks: roles/docker/tasks/ubuntu.yaml
  when: ansible_facts['board_vendor'] != 'Synology'

- name: Setup | Create Docker directories
  become: true
  ansible.builtin.file:
    path: "{{ docker_home }}"
    state: directory
    owner: root
    group: root # hmm.
    mode: '775'

- name: Setup | Ensure /etc/docker/ directory exists.
  become: true
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: 0755
  when: docker_daemon_options.keys() | length > 0
