---
- name: Get installed pip version
  command: "{{ pip_executable }} --version"
  register: pip_version_output
  ignore_errors: yes
  changed_when: false

- name: Install pip
  when: (pip_version_output is failed) or not pip_version_output.stdout is search(pip_version)
  shell: python -m ensurepip

# - name: Create a symbolic link
#   ansible.builtin.file:
#     become: true
#     src: /bin/pip3
#     dest: /bin/pip
#     state: link

- name: Install docker SDK
  pip:
    name: docker

# required for docker
- name: Install six
  pip:
    name: six

    # https://github.com/manojm321/ansible-synology/blob/main/roles/python/tasks/main.yaml


