---
- name: Get installed pip version
  ansible.builtin.command: "{{ pip_executable }} --version"
  register: pip_version_output
  ignore_errors: true
  changed_when: false

- name: Install pip
  when: (pip_version_output is failed) or not pip_version_output.stdout is search(pip_version)
  ansible.builtin.command: python -m ensurepip

- name: Install docker SDK
  ansible.builtin.pip:
    name: docker

# required for docker
- name: Install six
  ansible.builtin.pip:
    name: six
