- hosts: appservers
  vars_files:
    - default.config.yml
    - secrets.enc

  pre_tasks:
    - name: Setup | Create credential file (used for fstab entry)
      copy:
        content: |
          username={{ nas_media_user }}
          password={{ nas_media_pass }}
        dest: ~/.credential
        mode: 0600
      become: true

    - name: Setup | Mount shared volumes
      become: true
      ansible.posix.mount:
        src: "{{ item.src }}"
        path: "{{ item.dest }}"
        opts: "credentials=/root/.credential"
        state: mounted
        fstype: cifs
      loop: "{{ jellyfin_volumes }}"

  roles:
    - common
    - jellyfin
