servers:
  hosts:
    mbp1:
      ansible_host: 127.0.0.1
      ansible_connection: local
    mufasa.local:
      mqtt_installation_method: container
      mqtt_pid_file: /mosquitto/data/mosquitto.pid
      mqtt_allow_anonymous: true # TODO: Remove this option.
    rafiki.local:
      ansible_user: richard
      ansible_ssh_private_key_file: ~/.ssh/id_github_rsa
    192.168.88.200:
      ansible_user: root
    192.168.88.5:
      ansible_user: root
  children:
    appservers:
      hosts:
        mufasa.local:
    dns:
      hosts:
        192.168.88.2:
    storage:
      hosts:
        rafiki.local:
        zazu.local:
