servers:
  hosts:
    mbp1:
      ansible_host: 127.0.0.1
      ansible_connection: local
    mufasa.local:
      mqtt_installation_method: container
      mqtt_pid_file: /mosquitto/data/mosquitto.pid
      mqtt_allow_anonymous: true # TODO: Remove this option.
      ansible_user: "{{ ansible_user }}"
      ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"
    rafiki.local:
      ansible_user: "{{ ansible_user }}"
      ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"
  children:
    appservers:
      hosts:
        mufasa.local:
    dns:
      hosts:
        mufasa.local:
        rafiki.local:
    storage:
      hosts:
        rafiki.local:
        zazu.local:
