---
- hosts: mbp1
  connection: local
  gather_facts: false
  become: true

  vars:
    ansible_user_id: 1
    ansible_user_gid: 1
    ansible_machine: m1
  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
