---
# Simple ArgoCD installation with Traefik ingress
- name: Ensure ArgoCD namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ k3s_argocd_setup_namespace }}"
    state: present

- name: Ensure /tmp/argocd directory exists
  ansible.builtin.file:
    path: "/tmp/argocd"
    state: directory
    mode: '0755'

- name: Create values file from template
  ansible.builtin.template:
    src: "values.j2"
    dest: "/tmp/argocd-values.yaml"
    mode: '0644'

- name: Upload Chart.yml to the target node
  ansible.builtin.copy:
    src: "./files/Chart.yml"
    dest: "/tmp/argocd/Chart.yaml"
    mode: '0644'

- name: Render ArgoCD manifests from Helm chart
  kubernetes.core.helm_template:
    chart_ref: /tmp/argocd/
    include_crds: true
    release_name: "{{ k3s_argocd_setup_release_name }}"
    release_namespace: "{{ k3s_argocd_setup_namespace }}"
    dependency_update: true
    values_files:
      - "/tmp/argocd-values.yaml"
  register: argocd_manifests

- name: Apply ArgoCD manifests
  kubernetes.core.k8s:
    resource_definition: "{{ argocd_manifests.stdout }}"
    apply: true
    server_side_apply:
      field_manager: argocd-controller

- name: Wait for ArgoCD server to be ready
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: "{{ k3s_argocd_setup_release_name }}-server"
    namespace: "{{ k3s_argocd_setup_namespace }}"
  register: server_deployment
  until: server_deployment.resources[0].status.readyReplicas is defined and
         server_deployment.resources[0].status.readyReplicas > 0
  retries: 30
  delay: 10

- name: Check if ingress is accessible
  ansible.builtin.uri:
    url: "https://{{ k3s_argocd_setup_domain | default('argocd.home.lan') }}"
    method: GET
    status_code: 200, 302, 303, 307, 308
    validate_certs: no
    follow_redirects: yes
  register: argocd_accessibility
  retries: 10
  delay: 10
  until: argocd_accessibility.status in [200, 302, 303, 307, 308]
  ignore_errors: yes

- name: Display accessibility status
  ansible.builtin.debug:
    var: argocd_accessibility
  when: argocd_accessibility is defined

- name: Clean up temporary values file
  ansible.builtin.file:
    path: "/tmp/argocd-values.yaml"
    state: absent
