apiVersion: v1
kind: Secret
metadata:
    name: docmost-secrets
    namespace: tools
type: Opaque
stringData: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nj3djgkd6em9kdj26r39wenxjp707v637tx2wtlj3573uwq524mqex5w9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMHEwUFVudGpBOHc0cGsr
            R3IxSmtGQnZMNFNhZEZ6b2tFOTFOOTYweWg0Clc4blVkbjk4dit2RC84aGJXSTNW
            TnhTa21QZnhrRFZTMmdaSGVVMFBxN1kKLS0tIG9mdW1tRDcyL29IT0p2b1BoSkRo
            UFR1NEpUMW9wVU44RlF0ZXc2Q1FCcE0KGdk+KWppPwpX2ReQoiWTh9P0Gycy020v
            xvfHnSWGihTCC9vb43VURapAPhcrWWEoiCOFCMWBPL1Kb3yXdy1r+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-08T12:28:33Z"
    mac: ENC[AES256_GCM,data:opispP/FxCj68aVfpeOtNbn8esr37YQaZBeYOgIiTv4HDNHW6nq20p69oWZG6gjsXDl827nkDVJlOfT0PV+Uonx9il1Ru9RYZrI5Py9xvuNjpjXtjJenf5Y+r2JTPArhd4B1ZnZfoWqPwqXttQTO7hgmr//0kjBqR244K1mYSKY=,iv:tHavQC5YcNZWKaBR6EwcRo0x/yCNDX37QNY3CCbRO1c=,tag:dnT8DMa5whH44gTkCpRH8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets)$
    version: 3.9.4
