---
galaxy_info:
  author: rikdc
  description: Configures MySQL in a Docker container
  license: MIT
  min_ansible_version: "2.1"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags: []
dependencies: []
