---
# - name: Setup | Ensure the container user group exists
#   become: true
#   ansible.builtin.group:
#     name: "codeserver"
#     state: present
#     system: true

# - name: Setup | Ensure the container user exists
#   become: true
#   ansible.builtin.user:
#     name: "codeserver"
#     state: present
#     group: "codeserver"
#     create_home: false
#     system: true
#     shell: "/usr/sbin/nologin"

- name: Setup | Create Docker directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root # hmm.
    mode: '775'
  with_items:
    - "{{ code_server_root_directory }}"
    - "{{ code_server_config_directory }}"
    - "{{ code_server_projects_directory }}"

- name: Start Code Server
  community.docker.docker_container:
    name: "{{ code_server_container_name }}"
    image: linuxserver/code-server
    pull: true
    volumes: "{{ codeserver_mounts }}"
    ports:
      - "{{ code_server_port }}:8443"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      DEFAULT_WORKSPACE: "/code"
      PUID: "{{ code_server_user_id }}"
      PGID: "{{ code_server_group_id }}"
    restart_policy: unless-stopped
    memory: "{{ code_server_memory }}"
  when: code_server_enabled is true

- name: Stop Code Server
  community.docker.docker_container:
    name: "{{ code_server_container_name }}"
    state: absent
  when: code_server_enabled is false
