---
galaxy_info:
  author: rikdc
  description: Role to create Kubernetes PersistentVolumes and PersistentVolumeClaims
  company: Home Network

  license: MIT

  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - kubernetes
    - k8s
    - k3s
    - storage
    - nfs
    - persistent
    - volume

dependencies: []
