---
name: Secrets Scanning

on:
  push:
    branches: [main]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "41 22 * * 5"

jobs:
  Scan-for-secrets:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Whispers
        run: sudo pip install --ignore-installed whispers

      - name: Run scanner for the repository
        run: whispers ${{ github.workspace }} > /tmp/scan_output.json

      - name: Upload the scan output
        uses: actions/upload-artifact@v4
        with:
          name: scan_results
          path: /tmp/scan_output.json
          retention-days: 2
