---
name: Super-Linter

on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
  pull-requests: write

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Super-Linter
        uses: super-linter/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: ansible/inventory/(host_vars|group_vars)/.*
