---
name: Super-Linter

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  packages: read
  pull-requests: write
  checks: write
  statuses: write

jobs:
  super-lint-pr:
    name: Lint Changed Files
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
        with:
          show-progress: false
          fetch-depth: 0
          
      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}

      - name: Run Super-Linter (Changed Files Only)
        uses: super-linter/super-linter@v7.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_EXCLUDE: ansible/inventory/(host_vars|group_vars)/.*

  super-lint-push:
    name: Lint Full Codebase
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
        with:
          show-progress: false
          fetch-depth: 0

      - name: Run Super-Linter (Full Codebase)
        uses: super-linter/super-linter@v7.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true
          FILTER_REGEX_EXCLUDE: ansible/inventory/(host_vars|group_vars)/.*