---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-pki
spec:
  provider:
    vault:
      server: https://vault.home.lan:8200
      path: pki_homelab
      caProvider:
        type: ConfigMap
        name: vault-ca
        key: ca.crt
        namespace: external-secrets
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso-pki
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
